language: c
os:
  - linux
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
    - cmake
    - make
    - libuv1-dev
script:
  - (mkdir build && cd build && cmake .. && make)
  - (cd build && make CTEST_OUTPUT_ON_FAILURE=1 test)
