language: c
os:
  - linux
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
    - cmake
    - make
    - libuv1-dev
    - lcov
script:
  - (mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=1 .. && make coverage)
after_success:
  - bash <(curl -s https://codecov.io/bash)

