# This is a basic workflow to help you get started with Actions

name: 'Nightly Coverity'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
   - cron: '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "nightly_coverity"
  nightly_coverity:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.2.0
      with:
        stable_branch: 'master'
        development_branch: 'coverity_scan'
        allow_ff: true
        ff_only: true
        allow_forks: false
      env:
        GITHUB_TOKEN: ${{ secrets.NIGHTLY_COVERITY_TOKEN }}
